/**
 * Auto-generated by node-api-python from examples/fullstack/analytics.py
 * Do not edit manually — regenerate with:
 *   npx node-api-python generate-types ./examples/fullstack/analytics.py -o ./examples/fullstack/types/
 */

/** A single user analytics event. */
export interface UserEvent {
  user_id: string
  action: string
  page: string
  timestamp: number
}

/** Aggregated analytics report. */
export interface AnalyticsReport {
  unique_users: number
  total_events: number
  top_page: string
  by_action: Record<string, number>
  by_page: Record<string, number>
}

/**
 * Generate an analytics report from a list of user events.
 * @param events - List of user events to analyze
 * @returns Aggregated analytics report
 */
export function generate_report(events: UserEvent[]): Promise<AnalyticsReport>

/**
 * Filter events by criteria.
 * @param events - Events to filter
 * @param user_id - Filter by user ID (optional)
 * @param action - Filter by action type (optional)
 * @param page - Filter by page (optional)
 */
export function filter_events(
  events: UserEvent[],
  user_id?: string | null,
  action?: string | null,
  page?: string | null,
): Promise<UserEvent[]>
